### ISSUE TITLE
国のデータがありません。

### ISSUE THREAD

**Issue by martinheidegger** [baseinc/api-docs#3]
こんにちは！

API のをつかって[注文のデータ](https://github.com/baseinc/api-docs/blob/253b85e370b695f64eac05906674a5bf55594fa0/base_api_v1_orders_detail.md)は読むことができますが「国」というプロパティには入っていません。

![screenshot 2015-12-10 13 02 32](https://cloud.githubusercontent.com/assets/914122/11706692/517a446c-9f3e-11e5-8b23-e3912adcf7f8.png)

**Comment by basehibino** [comment]
oh!! 修正します！

**Comment by basehibino** [comment]
修正しました！

**Comment by martinheidegger** [comment]
すみません、今は国がついていますが "country"というフィルドには入力フォームと同じバリューが入っています。例えば  `Zaire (Democratic Republic of Co` 。国の名前は切れているし [Wikipedia のISO名前](https://en.wikipedia.org/wiki/ISO_3166-1)と違っています。プロセッシングしやすいバリュー、つまりISOのコードが別のフィルド: `country_code`があったら助かります。
